create table if not exists public.aliases (
  id bigint generated by default as identity primary key,
  alias text not null unique,
  meaning text not null
);

alter table public.aliases enable row level security;

drop policy if exists aliases_select_read_all on public.aliases;

create policy aliases_select_read_all
  on public.aliases
  for select
  to anon, authenticated
  using (true);

grant select on table public.aliases to anon, authenticated;

revoke insert, update, delete, truncate, references, trigger
  on table public.aliases
  from anon, authenticated;
